### ISSUE TITLE
TransE exception during training

### ISSUE THREAD

**Issue by luigiba** [SANSA-Stack/SANSA-ML#18]
Dear Sansa Team,
I'm trying to run TransE.scala algorithm using the script kge/linkprediction/run/TransERun.scala. 
I got the following exception: 
`Exception in thread "main" java.lang.IllegalArgumentException: requirement failed
	at scala.Predef$.require(Predef.scala:212)
	at com.intel.analytics.bigdl.tensor.DenseTensorMath$.cadd$mFc$sp(DenseTensorMath.scala:128)
	at com.intel.analytics.bigdl.tensor.DenseTensor$mcF$sp.add$mcF$sp(DenseTensor.scala:906)
	at com.intel.analytics.bigdl.tensor.DenseTensor$mcF$sp.add(DenseTensor.scala:906)
	at com.intel.analytics.bigdl.tensor.DenseTensor$mcF$sp.add(DenseTensor.scala:30)
	at com.intel.analytics.bigdl.optim.Adam$mcF$sp.optimize$mcF$sp(Adam.scala:76)
	at net.sansa_stack.ml.spark.kge.linkprediction.models.TransE$$anonfun$run$1.apply$mcVI$sp(TransE.scala:66)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
	at net.sansa_stack.ml.spark.kge.linkprediction.models.TransE.run(TransE.scala:52)
	at net.sansa_stack.ml.spark.kge.linkprediction.run.TransERun$.main(TransERun.scala:42)
	at net.sansa_stack.ml.spark.kge.linkprediction.run.TransERun.main(TransERun.scala)`

It seems that TransE.scala:52 raised the exception, i.e. the optimization step for relations:
`opt.optimize(delta, r)`
How can I solve this?
Thanks in advance for your reply

**Comment by afshinsadeghi** [comment]
Hi @luigiba . 

This code is in dev branch which means it is not thoroughly tested, but let's give it a try. :) 

Can you explain the steps to reproduce this error? Also, before that, have you set the path in the line 26 of 
"sansa-ml-spark/src/main/scala/net/sansa_stack/ml/spark/kge/linkprediction/run/TransERun.scala"  to a  triple file in your computer?

**Comment by afshinsadeghi** [comment]
I ran the file on a triple dataset and it did not give the mentioned error.  Please as said above set the file in line number 26 first.
